# Generated by Django 5.1.4 on 2025-05-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='logo',
            field=models.ImageField(upload_to='program_logos/'),
        ),
    ]
