# Generated by Django 5.1.4 on 2025-05-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_crud', '0002_alter_program_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
