# Generated by Django 5.1.4 on 2025-05-29 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_crud', '0003_alter_program_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='logo',
            field=models.ImageField(upload_to='program_logos/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
