# Generated by Django 5.1.4 on 2025-05-29 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_crud', '0004_alter_program_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='logo',
            field=models.FileField(upload_to='program_logos/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
